### ISSUE TITLE
Index crowdloan data

### ISSUE THREAD

**Issue by bdmason** [litentry/squid#31]
Take a look at the [pallet](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/crowdloan.rs) and the [wiki](https://wiki.polkadot.network/docs/learn-crowdloans). We want to cover all the data if possible.

A very vague overview is:

Slot auctions get created, people initiate crowdloans (using a parachain ID), users contribute DOT or Kusama tokens, the winner for each slot (chosen by candle auction) gets a parachain.

**Comment by geastwood** [comment]
I think this is already done yeh, @bdmason

**Comment by bdmason** [comment]
Sorry for the late reply! Yeah it is
