### ISSUE TITLE
Set up pallet action logger

### ISSUE THREAD

**Issue by bdmason** [litentry/squid#40]
Approaching new pallets is a challenge because the information is quite hard to pin down, meaning the research phase is way longer than the development phase.

The plan is to build a test processor. The requirements are:

- only runs actions involving a specified account
- logs all events/extrinsics for a pallet (to a JSON file)
- has a configurable chain -> run against small chain at first, then against a bigger chain (e.g. polkadot/kusama) when we are the confirmation stage
- set block range

@markdavison feel free to add/edit details

**Comment by markdavison** [comment]
It might be helpful to be able to set a block range that you want to be fetched?

**Comment by bdmason** [comment]
> It might be helpful to be able to set a block range that you want to be fetched?

added, it's an easy param to set
