### ISSUE TITLE
Data requirement: Khala chain council membership

### ISSUE THREAD

**Issue by kaylawangnow** [litentry/squid#65]
Hi Mark here is a new data requirement:

Name: Khala chain council membership
Description: Khala blockchain council membership judgement
Blockchain: Khala
Type: Kusama parachain
Data origin: Khala blockchain on-chain governance council member list
Requirement: give an address and judge whether it is a Khala blockchain on-chain governance council member
Result format: Y/N
Generic requirement: applicable to all Polkadot and Kusama parachain
Expecting finish time:  Before April

cc @bdmason

**Comment by markdavison** [comment]
This is not quite in line with your request... but I think it should be possible to achieve the same result.

This query:

https://graph.litentry.io/graphql?query=query%20MyQuery%20%7B%0A%20%20substrateChainCouncil%20%7B%0A%20%20%20%20members%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

Gives you all current members addresses. Will that work for your requirements?

**Comment by markdavison** [comment]
Are we ok to mark this as Done @kaylawangnow ?

**Comment by kaylawangnow** [comment]
yes thank u
