### ISSUE TITLE
Data requirement: Khala chain proposal submitting times

### ISSUE THREAD

**Issue by kaylawangnow** [litentry/squid#66]
Hi Mark another data requirement:

Name: Khala Governance Proposal Commits
Description: Khala blockchain governance proposal submission counts
Blockchain: Khala
Type: Kusama parachain
Data origin: Khala blockchain on-chain governance proposals, all types of proposals
Requirement: give an address and return number of Khala blockchain governance proposal submission counts
Result format: number
Generic requirement: applicable to all Polkadot and Kusama parachain
Expecting finish time: Before April

Litentry Graph dev: [@markdavison](https://github.com/markdavison)
MCP subject implement dev: [@Hiwg](https://github.com/Hiwg)
cc @bdmason

**Comment by markdavison** [comment]
This query should fulfill your requirement:

https://graph.litentry.io/graphql?operationName=MyQuery&query=query%20MyQuery%20%7B%0A%20%20substrateGovernanceAccountById(id%3A%20%22H9eSvWe34vQDJAWckeTHWSqSChRat8bgKHG39GC1fjvEm7y%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20totalTechnicalCommitteeProposals%0A%20%20%20%20totalDemocracyProposals%0A%20%20%20%20totalCouncilProposals%0A%20%20%20%20network%0A%20%20%20%20councilProposals(limit%3A%2010)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20threshold%0A%20%20%20%20%20%20proposalIndex%0A%20%20%20%20%20%20proposalHash%0A%20%20%20%20%20%20date%0A%20%20%20%20%20%20blockNumber%0A%20%20%20%20%7D%0A%20%20%20%20democracyProposals(limit%3A%2010)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20amount%0A%20%20%20%20%20%20blockNumber%0A%20%20%20%20%20%20date%0A%20%20%20%20%20%20proposalIndex%0A%20%20%20%20%7D%0A%20%20%20%20technicalCommitteeProposals(limit%3A%2010)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20threshold%0A%20%20%20%20%20%20proposalIndex%0A%20%20%20%20%20%20proposalHash%0A%20%20%20%20%20%20date%0A%20%20%20%20%20%20blockNumber%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

**Comment by markdavison** [comment]
Are we ok to mark this as Done @kaylawangnow ?

**Comment by kaylawangnow** [comment]
yes, thanks!
